name: 'Bryan Clark'
description: 'Extracts all the ZD- references from issue comments'
author: '@github'
inputs:
  token:
    description: 'Use the ${{ secrets.GITHUB_TOKEN }} value'
runs:
  using: 'node12'
  main: 'dist/index.js'
