name: 'Bryan Clark'
description: 'Extracts all the ZD- references from issue comments'
author: '@github'
inputs:
  token:
    description: 'Pass the GITHUB_TOKEN'
runs:
  using: 'node12'
  main: 'dist/index.js'
