name: Find Issue Zendesk References
on:
  issue_comment:
    types: [created, deleted, edited]
  issues:
    types: [opened, edited]

jobs:
  zendesk:
    runs-on: ubuntu-latest
    steps:
      - uses: clarkbw/extract-zds@master
        id: find-zds
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Get All ZD ids
        run: echo "${{steps.find-zds.outputs.result}}"
